name: environment_map
description: 'Return correct environment string for docker image tagging'
inputs:
  github_ref:
    description: 'Current branch or tag'
    required: false

outputs:
  environment:
    description: "Environment string"
  altEnvironment:
    description: "Environment string compatible with cluster module"
  subdomain:
    description: "Environment specific string for use in URIs"
  shortBranchName:
    description: "GitHub ref as processed"

runs:
  using: 'node12'
  main: 'index.js'
